### ISSUE TITLE
Restore minSDK to 7

### ISSUE THREAD

**Issue by intrications** [intrications/intent-intercept#17]
This is a developer tool. It should probably work on the widest range of devices.

**Comment by intrications** [comment]
@k3b Please can you test the latest code which should work back to API 7 with a fallback theme where Material Design isn't available.

**Comment by k3b** [comment]
note: the ticket should be renamed to Restore minSDK to 7 (not 17)

Is there a reason why you want to use "SettingsActivity extends ActionBarActivity" with "SettingsFragment extends PreferenceFragment" in newer android versions?

"Pre15SettingsActivity extends PreferenceActivity" will also work with newer devices (at least on my android 4.4 device).

That way there would be no need for StartUpActivity that decides which settings version to launch.

--------------------

I have tested your last code changes: 

on my android 2.2 device Pre15SettingsActivity crashes when calling SettingsFragment.setupSettings because "SettingsFragment extends PreferenceFragment" cannot be created. 

After moving setupSettings to Pre15SettingsActivity the code worked as expected.

**Comment by intrications** [comment]
I am using "SettingsActivity extends ActionBarActivity" with "SettingsFragment extends PreferenceFragment" so I can use Material Design with an ActionBar.

Unless you are seeing something different "Pre15SettingsActivity extends PreferenceActivity" doesn't have have an ActionBar and looks ugly using the original Android theme. This is acceptable on pre-API 15 devices but I have no desire to see it on modern versions of Android.

If you can find another way to do this then please send a pull request.

I have pushed code which should fix the crash.

**Comment by intrications** [comment]
Closing because minSdk 8 is good enough.
